version: "3"

services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      # ENV
      DIRECTUS_APP_ENV: "production"
      # LOGIN
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # SECURITY
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      # DATABASE
      DB_CLIENT: ${DIRECTUS_DATABASE_CLIENT}
      DB_HOST: ${DIRECTUS_DATABASE_HOST}
      DB_PORT: ${DIRECTUS_DATABASE_PORT}
      DB_DATABASE: ${DIRECTUS_DATABASE_NAME}
      DB_USER: ${DIRECTUS_DATABASE_USERNAME}
      DB_PASSWORD: ${DIRECTUS_DATABASE_PASSWORD}
      # FILE STORAGE
      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_S3_DRIVER: ${STORAGE_S3_DRIVER}
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}

    volumes:
      - ./extensions:/directus/extensions 