AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack
Resources:
  database:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/root-fl-storage/cloudformation/c5a6847895b656dbc4f2ac2a4aacfb66.template
  storage:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/root-fl-storage/cloudformation/01029586ebd991262e257ce7dd5e539b.template
  App:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/root-fl-storage/cloudformation/d9bdff8b20058f2200f9add56b0f3be0.template
      Parameters:
        RdsAddress:
          Fn::GetAtt:
          - database
          - Outputs.Endpoint
        RdsPort:
          Fn::GetAtt:
          - database
          - Outputs.Endpoint
        BucketName:
          Fn::GetAtt:
          - storage
          - Outputs.BucketName
        AccessKeyID:
          Fn::GetAtt:
          - storage
          - Outputs.AccessKeyID
        SecretAccessKey:
          Fn::GetAtt:
          - storage
          - Outputs.SecretAccessKey
