AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack
Parameters:
  DirectusKey:
    Type: String
    NoEcho: true
  DirectusSecret:
    Type: String
    NoEcho: true
  DirectusUsername:
    Type: String
    NoEcho: true
  DirectusDatabaseName:
    Type: String
    NoEcho: true
  DirectusPassword:
    Type: String
    NoEcho: true
  DirectusClient:
    Type: String
  AdminEmail:
    Type: String
  AdminPassword:
    Type: String
Resources:
  database:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/root-fl-storage/cloudformation/235d285929f17c9e931358d4174e04e4.template
      Parameters:
        DirectusUsername:
          Ref: DirectusUsername
        DirectusPassword:
          Ref: DirectusPassword
        DirectusDatabaseName:
          Ref: DirectusDatabaseName
        DirectusClient:
          Ref: DirectusClient
  storage:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/root-fl-storage/cloudformation/01029586ebd991262e257ce7dd5e539b.template
  App:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/root-fl-storage/cloudformation/81f53789513d37a6ee6d3397146b9268.template
      Parameters:
        DirectusKey:
          Ref: DirectusKey
        DirectusSecret:
          Ref: DirectusSecret
        DirectusUsername:
          Ref: DirectusUsername
        DirectusPassword:
          Ref: DirectusPassword
        DirectusDatabaseName:
          Ref: DirectusDatabaseName
        DirectusClient:
          Ref: DirectusClient
        AdminEmail:
          Ref: AdminEmail
        AdminPassword:
          Ref: AdminPassword
        RdsAddress:
          Fn::GetAtt:
          - database
          - Outputs.Endpoint
        RdsPort:
          Fn::GetAtt:
          - database
          - Outputs.Port
        BucketName:
          Fn::GetAtt:
          - storage
          - Outputs.BucketName
        AccessKeyID:
          Fn::GetAtt:
          - storage
          - Outputs.AccessKeyID
        SecretAccessKey:
          Fn::GetAtt:
          - storage
          - Outputs.SecretAccessKey
