AWSTemplateFormatVersion: "2010-09-09"
Description: APP creation and configuration

Parameters:
    RdsAddress: 
      Type: String
    RdsPort:
      Type: String
    BucketName: 
      Type: String
    AccessKeyID: 
      Type: String
    SecretAccessKey: 
      Type: String
    DirectusUsername:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_USERNAME
    DirectusPassword:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_PASSWORD
    DirectusDatabaseName:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_NAME
    DirectusClient:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_CLIENT

Resources:
  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For ssh on port 22 access and 8080 port access for App
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0

  App:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0333305f9719618c7
      KeyName: Directus
      SecurityGroups:
        - !Ref AppSG
      UserData: 
        Fn::Base64: !Sub
           | 
            #!/bin/bash

            sudo bash

            DIRECTUS_DATABASE_HOST=${RdsAddress} >> .env
            DIRECTUS_DATABASE_PORT=${RdsPort} >> .env
            DIRECTUS_DATABASE_CLIENT=${DirectusClient} >> .env
            DIRECTUS_DATABASE_NAME=${DirectusDatabaseName} >> .env
            DIRECTUS_DATABASE_PASSWORD=${DirectusPassword} >> .env
            DIRECTUS_DATABASE_USERNAME=${DirectusUsername} >> .env
            DIRECTUS_KEY={{resolve:ssm-secure:DIRECTUS_KEY:1}} >> .env
            DIRECTUS_SECRET={{resolve:ssm-secure:DIRECTUS_SECRET:1}} >> .env
            ADMIN_EMAIL={{resolve:ssm-secure:ADMIN_EMAIL:1}} >> .env
            ADMIN_PASSWORD={{resolve:ssm-secure:ADMIN_PASSWORD:1}} >> .env
            STORAGE_S3_KEY=${AccessKeyID} >> .env
            STORAGE_S3_SECRET=${SecretAccessKey} >> .env
            STORAGE_S3_BUCKET=${BucketName} >> .env
            STORAGE_LOCATIONS=s3 >> .env
            STORAGE_S3_DRIVER=s3 >> .env
            STORAGE_S3_REGION=eu-west-1 >> .env

            # Install docker
            apt-get update
            apt-get install -y cloud-utils apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            apt-get update
            apt-get install -y docker-ce
            usermod -aG docker ubuntu

            # Install docker-compose
            curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

            # Clone and run a sample application
            mkdir projects
            cd projects/
            git clone https://github.com/francoislongatte/Directus.git
            cd Directus

            sudo docker-compose --file docker-compose.yaml up

Outputs:
  PublicIp:
    Value: !GetAtt App.PublicIp