AWSTemplateFormatVersion: "2010-09-09"
Description: APP creation and configuration

Resources:
  Parameters:
    VPCName:
      Type: String
    RdsAddress: 
      Type: String
    RdsPort:
      Type: String

  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For ssh on port 22 access and 8080 port access for App
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
          
  App:
    type: AWS::EC2::Instance
    properties:
      InstanceType: t2.micro
      ImageId:
      KeyName:
      SecurityGroups:
        - !Ref AppSG
      VPCSecurityGroups: 
        - [ !Ref VPCName ]
      UserData: 
        Fn::Base64:
          !Sub | 
            #!/bin/bash
            yum update -y

            # Install Docker
            amazon-linux-extras install docker -y
            service docker start
            systemctl enable docker
            usermod -a -G docker ec2-user
            chmod 666 /var/run/docker.sock

            # Install Docker Compose
            curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

            # Mount Drive
            mkdir /data
            mkfs -t xfs /dev/xvdh
            mount /dev/xvdh /data

            # Install git in your EC2 instance
            yum install git -y

            # Clone and run a sample application
            cd ~
            git clone https://github.com/francoislongatte/Directus.git
            cd Directus
            docker-compose --file docker-compose.yaml up

  Outputs:
    Endpoint:
      Value: !GetAtt RdsInstance.Endpoint.Address
      Export:
       Name: RdsAddress
    Port:
      Value: !GetAtt RdsInstance.Endpoint.Port
      Export:
       Name: RdsPort