AWSTemplateFormatVersion: "2010-09-09"
Description: APP creation and configuration

Parameters:
    RdsAddress: 
      Type: String
    RdsPort:
      Type: String
    BucketName: 
      Type: String
    AccessKeyID: 
      Type: String
    SecretAccessKey: 
      Type: String
    DirectusUsername:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_USERNAME
    DirectusPassword:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_PASSWORD
    DirectusDatabaseName:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_NAME
    DirectusClient:
      Type: AWS::SSM::Parameter::Value<String>
      Default: DIRECTUS_DATABASE_CLIENT

Resources:
  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For ssh on port 22 access and 8080 port access for App
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0

  App:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0333305f9719618c7
      KeyName: Directus
      SecurityGroups:
        - !Ref AppSG
      UserData: 
        Fn::Base64: !Sub
           | 
            #!/bin/bash

            # Install docker
            sudo apt-get update
            sudo apt-get remove docker docker-engine docker.io
            sudo apt install docker.io

            sudo systemctl start docker
            sudo systemctl enable docker

            sudo usermod -aG docker ubuntu

            # composer download and Install
            # Install docker-compose
            sh -c "curl -L http://github.com/docker/compose/releases/download/v2.15.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
            sh -c "curl -L http://raw.githubusercontent.com/docker/compose/v2.15.1/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"
            chmod a+rx '/usr/local/bin/docker-compose'

            # Clone and run a sample application
            mkdir projects
            cd projects/
            git clone https://github.com/francoislongatte/Directus.git
            cd Directus

            DIRECTUS_DATABASE_HOST=${RdsAddress} \
            DIRECTUS_DATABASE_PORT=${RdsPort} \
            DIRECTUS_DATABASE_CLIENT=${DirectusClient} \
            DIRECTUS_DATABASE_NAME=${DirectusDatabaseName} \
            DIRECTUS_DATABASE_PASSWORD=${DirectusPassword} \
            DIRECTUS_DATABASE_USERNAME=${DirectusUsername} \
            DIRECTUS_KEY={{resolve:ssm-secure:DIRECTUS_KEY:1}} \
            DIRECTUS_SECRET={{resolve:ssm-secure:DIRECTUS_SECRET:1}} \
            ADMIN_EMAIL={{resolve:ssm-secure:ADMIN_EMAIL:1}} \
            ADMIN_PASSWORD={{resolve:ssm-secure:ADMIN_PASSWORD:1}} \
            STORAGE_S3_KEY=${AccessKeyID} \
            STORAGE_S3_SECRET=${SecretAccessKey} \
            STORAGE_S3_BUCKET=${BucketName} \
            STORAGE_LOCATIONS=s3 \
            STORAGE_S3_DRIVER=s3 \
            STORAGE_S3_REGION=eu-west-1 \
            docker-compose --file docker-compose.yaml up >> docker.sh

Outputs:
  PublicIp:
    Value: !GetAtt App.PublicIp