AWSTemplateFormatVersion: "2010-09-09"
Description: RDS creation and configuration

Resources:
  Parameters:
    VPCName:
      Type: String
    DirectusUsername:
      Type: AWS::SSM::Parameter::DIRECTUS_DATABASE_USERNAME<String>
    DirectusPassword:
      Type: AWS::SSM::Parameter::DIRECTUS_DATABASE_PASSWORD<String>
    DirectusDatabaseName:
      Type: AWS::SSM::Parameter::DIRECTUS_DATABASE_NAME<String>
    DirectusClient:
      Type: AWS::SSM::Parameter::DIRECTUS_DATABASE_CLIENT<String>

  RdsSG:
    type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Database Group
      DbSecurityGroupIngress:
        - CIDRIP: 0.0.0.0/0

  RdsInstance:
    type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DirectusDatabaseName
      Engine: !Ref DirectusClient
      MasterUsername: !Ref DirectusUsername
      MasterUserPassword: !Ref DirectusPassword
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: '1'
      DBSecurityGroups:
        - !Ref RdsSG
      VPCSecurityGroups: 
        - [ !Ref VPCName ]
  
  Outputs:
    Endpoint:
      Value: !GetAtt RdsInstance.Endpoint.Address
      Export:
       Name: RdsAddress
    Port:
      Value: !GetAtt RdsInstance.Endpoint.Port
      Export:
       Name: RdsPort