AWSTemplateFormatVersion: "2010-09-09"
Description: RDS creation and configuration

Parameters:
    DirectusUsername:
      Type: String
    DirectusPassword:
      Type: String
    DirectusDatabaseName:
      Type: String
    DirectusClient:
      Type: String

Resources:
  RdsInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DBInstanceIdentifier: !Ref DirectusDatabaseName
      BackupRetentionPeriod: 30
      DBName: !Ref DirectusDatabaseName
      Engine: !Ref DirectusClient
      MasterUsername: !Ref DirectusUsername
      MasterUserPassword: !Ref DirectusPassword
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 20
  
Outputs:
  Endpoint: 
    Value: !GetAtt RdsInstance.Endpoint.Address
  Port: 
    Value: !GetAtt RdsInstance.Endpoint.Port