AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack

Resources:
  database:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: database.yaml
  
  storage:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: storage.yaml
  
  App:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: app.yaml
      Parameters: 
        RdsAddress: 
          Fn::GetAtt: [database, Outputs.Endpoint]
        RdsPort: 
          Fn::GetAtt: [database, Outputs.Endpoint]
        BucketName: 
          Fn::GetAtt: [storage, Outputs.BucketName]
        AccessKeyID:
          Fn::GetAtt: [storage, Outputs.AccessKeyID]
        SecretAccessKey:
          Fn::GetAtt: [storage, Outputs.SecretAccessKey]