AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack

Resources:

  Parameters:
    VPCName:
      Description: VPC name
      value: !Ref DirectusVpc
      Type: String

  DirectusVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 0.0.0.0/0
    
  databaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./database.yaml
      Parameter: 
        VPCName: !Ref VPCName
  
  storageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./storage.yaml
      Parameter: 
        VPCName: !Ref VPCName
  
  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./app.yaml
      Parameter: 
        VPCName: !Ref VPCName
        RdsAddress: !ImportValue RdsAddress
        RdsPort: !ImportValue RdsPort
        BucketName: !ImportValue BucketName
        AccessKeyID: !ImportValue AccessKeyID
        SecretAccessKey: !ImportValue SecretAccessKey