AWSTemplateFormatVersion: '2010-09-09'

Resources:

  Parameters:
    VPCName:
      Description: VPC name
      value: !Ref DirectusVpc
      Type: String

  DirectusVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 0.0.0.0/0
    
  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./database.yaml
      Parameter: 
        VPCName: !Ref VPCName
  
  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./app.yaml
      Parameter: 
        VPCName: !Ref VPCName
        RdsAddress: !ImportValue RdsAddress
        RdsPort: !ImportValue RdsPort